version: '3.2'

services:
  mariadbtest:
    restart: always
    env_file: .dbenv
    build:
      context: mariadb
      dockerfile: Dockerfile.test
    hostname: "dbserver"
    ports:
      - "3307:3306"
    expose:
      - "3307"
    networks:
      - test_network
  phpmyadmintest:
    image: phpmyadmin
    container_name: phpmyadmintest
    environment:
     - PMA_ARBITRARY=1
    ports:
     - 8080:80
    volumes:
     - /sessions
    networks:
      - test_network
    depends_on: 
      - mariadbtest
  webapptest:
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    hostname: "dashboard"
    volumes:
      - /gfdlhome:/home:ro
      - /nbhome:/nbhome:ro
      - type: bind
        source: /archive
        target: /archive
        read_only: true
        bind:
            propagation: slave      
    ports:
      - "5600:5050"
    networks:
      - test_network
    depends_on: 
      - mariadbtest

networks:
  test_network:
    driver: bridge
